services:
  - type: web
    name: chatify-app
    env: node
    buildCommand: |
      npm install --prefix frontend
      npm run build --prefix frontend
      npm install --prefix backend
    startCommand: node backend/server.js
    buildFilter:
      paths:
        - frontend/**
        - backend/**
